
import Providers from './components/general/Providers'
import Navbar from './components/navbar/Navbar'
import './globals.css'

export const metadata = {
  title: 'Simple Work',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen w-screen fix'>
       <Providers>
         {children}
       </Providers>
       
      </body>
    </html>
  )
}
