
import Navbar from './components/navbar/Navbar'
import './globals.css'

export const metadata = {
  title: 'Simple Work',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='absolute h-screen w-screen overflow-hidden'>
        {children}
      </body>
    </html>
  )
}
